In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns

In [2]:
cancer_data=pd.read_csv("C://Users//User//Downloads//Cancer.csv")

In [3]:
cancer_data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [4]:
print(cancer_data.keys())

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')


In [5]:
Creat1=cancer_data.drop('id',axis=1)

In [6]:
Creat1

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [7]:
X=Creat1[['radius_mean','texture_mean', 'perimeter_mean','area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean','concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]
y=Creat1['diagnosis']

In [8]:
X1=X.values
X1 = (X1 - np.mean(X1,axis=0)) / np.std(X1,axis=0)

In [9]:
X1

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [10]:
from sklearn import model_selection

In [11]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X1, y, test_size = 0.2, random_state = 1000)

In [12]:
from sklearn import svm

In [13]:
svcModel=svm.SVC(kernel='linear', C=1,probability=True)

In [14]:
svcModel.fit(X_train, y_train)

SVC(C=1, kernel='linear', probability=True)

In [15]:
predicted=svcModel.predict(X_test)

In [16]:
predicted

array(['M', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [17]:
accuracy = svcModel.score(X_train, y_train)

In [18]:
accuracy

0.9868131868131869

In [19]:
from sklearn.metrics import f1_score

In [20]:
print(f1_score(y_test, predicted,average='micro'))

0.9649122807017544


Do lime

In [21]:
num_perturb = 569
X_limePart = np.random.normal(0,1,size=(num_perturb,X.shape[1]))

In [22]:
X_limePart

array([[ 5.24530880e-01, -2.00984970e+00,  2.35211055e+00, ...,
         1.95021533e-01, -4.56179367e-01,  1.15708057e+00],
       [ 9.24973693e-02, -7.63207413e-01, -1.19269986e+00, ...,
         1.33996032e-01, -7.77300085e-01, -1.17808511e+00],
       [ 1.66212201e-01, -1.21734058e+00,  1.09047686e+00, ...,
         5.60852367e-01, -1.83810482e-01,  4.83293907e-02],
       ...,
       [-1.39139723e+00,  1.02955004e+00,  9.60189742e-01, ...,
         1.44955629e+00,  5.76278909e-01,  4.13877743e-01],
       [-9.27049045e-01,  8.54043843e-01,  1.63899914e-01, ...,
        -9.35723914e-01, -2.05006577e+00, -6.86252967e-04],
       [ 1.79927059e-01,  5.68669869e-01,  3.15132302e-01, ...,
        -9.66409195e-01,  1.09871451e-03, -2.30600585e-02]])

In [23]:
X_limePart1=(X_limePart)*np.std(X1,axis=0)+X

In [24]:
dfX_limePart=pd.DataFrame(X_limePart1,columns=['radius_mean','texture_mean', 'perimeter_mean','area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean','concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst'])

In [25]:
result=dfX_limePart

In [26]:
y2 = svcModel.predict_proba(result)

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


In [27]:
original_data=np.array(X_test[0])

In [28]:
original_data

array([ 1.00901958,  0.33750653,  1.04750661,  0.87828988,  1.07742478,
        1.17800531,  1.2140743 ,  1.45686615,  0.58189236, -0.16126803,
        1.46580104,  0.33229087,  1.32368253,  1.17869585,  0.66536734,
        1.34480634,  0.66865393,  1.07283249, -0.334455  ,  0.44372519,
        0.8699144 , -0.09236878,  0.76367278,  0.74081408,  0.41343409,
        0.6077358 ,  0.41312203,  0.56176669, -0.7081927 , -0.36385013])

In [29]:
original_data.reshape(1,30)

array([[ 1.00901958,  0.33750653,  1.04750661,  0.87828988,  1.07742478,
         1.17800531,  1.2140743 ,  1.45686615,  0.58189236, -0.16126803,
         1.46580104,  0.33229087,  1.32368253,  1.17869585,  0.66536734,
         1.34480634,  0.66865393,  1.07283249, -0.334455  ,  0.44372519,
         0.8699144 , -0.09236878,  0.76367278,  0.74081408,  0.41343409,
         0.6077358 ,  0.41312203,  0.56176669, -0.7081927 , -0.36385013]])

In [30]:
import sklearn
import sklearn.metrics

In [31]:
distances = sklearn.metrics.pairwise_distances(result.values,original_data.reshape(1,30), metric='cosine').ravel()

In [32]:
print(distances)

[0.73253321 0.73303892 0.72535668 0.70535467 0.72063504 0.71684476
 0.7317743  0.71730351 0.71474662 0.71614456 0.72469889 0.72907181
 0.71034755 0.71314831 0.7100782  0.71987599 0.72773186 0.728498
 0.7418714  0.71298316 0.71115377 0.68943606 0.71677805 0.74404073
 0.75011642 0.7207435  0.71866185 0.71821503 0.73020058 0.71952278
 0.72545104 0.72617721 0.7241002  0.73298197 0.72975507 0.72505505
 0.71456486 0.70747826 0.69186885 0.71618725 0.7178488  0.71004654
 0.72236492 0.72354039 0.71783048 0.72603657 0.69044834 0.717639
 0.70697377 0.71367797 0.70179813 0.71382988 0.70986889 0.71845719
 0.72429647 0.7031428  0.7390522  0.72108111 0.70772887 0.68984123
 0.68997589 0.68254824 0.7144498  0.6839085  0.72434997 0.71871328
 0.69397557 0.70365304 0.69271037 0.7090333  0.73126687 0.67430422
 0.7361376  0.71909802 0.71511536 0.7205551  0.70418443 0.72115344
 0.71657258 0.71174987 0.70621537 0.70755261 0.72992121 0.71826817
 0.71265254 0.72751698 0.71357491 0.73054772 0.7062135  0.70990304

In [33]:
distances.shape

(569,)

In [34]:
kernel_width = 0.25
weights = np.sqrt(np.exp(-(distances**2)/kernel_width**2)) #Kernel function
print(weights)

[0.01366607 0.01358528 0.01485916 0.01868187 0.01569334 0.0163925
 0.0137881  0.01630645 0.01679118 0.01652461 0.01497298 0.01423053
 0.01765477 0.01710056 0.01770889 0.01583122 0.0144545  0.01432607
 0.01224074 0.01713281 0.01749365 0.0223132  0.01640505 0.01192912
 0.01109349 0.01567373 0.01605397 0.01613664 0.01404424 0.01589574
 0.0148429  0.01471826 0.01507724 0.01359436 0.01411751 0.01491126
 0.01682611 0.0182388  0.02172134 0.01651653 0.01620468 0.01771526
 0.01538306 0.01517531 0.01620809 0.01474232 0.02206525 0.01624377
 0.01834322 0.01699748 0.01944501 0.01696802 0.01775105 0.01609179
 0.01504299 0.01915334 0.01265649 0.01561281 0.01818713 0.02221367
 0.02218067 0.02406548 0.01684826 0.02371028 0.01503367 0.01604448
 0.02121988 0.01904366 0.02151981 0.01792022 0.01387024 0.02631834
 0.0130994  0.01597364 0.0167205  0.01570781 0.01893003 0.01559978
 0.01644374 0.01737535 0.01850117 0.01822346 0.01409014 0.01612679
 0.01719754 0.01449071 0.0170175  0.01398738 0.01850156 0.01774

In [35]:
weights.shape

(569,)

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
simpler_model = LinearRegression()
simpler_model.fit(X=result, y=y2, sample_weight=weights)

LinearRegression()

In [38]:
simpler_model.coef_

array([[ 1.17206750e-44,  1.55245483e-45,  2.10049104e-45,
        -2.51648189e-46, -7.92171965e-46,  1.37436344e-45,
        -8.18153732e-48,  1.09072280e-46,  4.91298125e-46,
         1.62959521e-45, -4.40180377e-46,  2.21086500e-45,
        -4.99350295e-46,  1.55932975e-46,  1.33765586e-45,
         9.48909074e-47,  3.30699460e-46, -9.66094610e-46,
        -3.39416499e-46,  9.28041464e-46,  7.03264487e-45,
        -1.00270075e-45, -1.95139827e-45,  4.39900169e-47,
        -4.76182137e-46,  7.20530503e-47, -1.45680619e-46,
        -8.42090195e-46,  4.67516361e-46, -6.57539537e-46],
       [ 1.44394396e-30,  1.93868451e-31,  2.69843980e-31,
        -3.13851900e-32, -7.99710222e-32,  1.69852412e-31,
         2.96298507e-32,  5.41561011e-34,  6.96147872e-32,
         2.05793219e-31, -7.72532205e-32,  2.37522025e-31,
        -4.11252054e-32,  1.88369555e-32,  1.42910582e-31,
         3.08928204e-32,  3.15785010e-32, -1.24619777e-31,
        -4.72146315e-32,  1.19712585e-31,  8.24546098e-

In [39]:
simpler_model.coef_2=abs(simpler_model.coef_[0])

In [40]:
simpler_model.coef_2

array([1.17206750e-44, 1.55245483e-45, 2.10049104e-45, 2.51648189e-46,
       7.92171965e-46, 1.37436344e-45, 8.18153732e-48, 1.09072280e-46,
       4.91298125e-46, 1.62959521e-45, 4.40180377e-46, 2.21086500e-45,
       4.99350295e-46, 1.55932975e-46, 1.33765586e-45, 9.48909074e-47,
       3.30699460e-46, 9.66094610e-46, 3.39416499e-46, 9.28041464e-46,
       7.03264487e-45, 1.00270075e-45, 1.95139827e-45, 4.39900169e-47,
       4.76182137e-46, 7.20530503e-47, 1.45680619e-46, 8.42090195e-46,
       4.67516361e-46, 6.57539537e-46])

In [41]:
feature_nameintxt=['radius_mean','texture_mean', 'perimeter_mean','area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean','concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst']
featurecoef=zip(feature_nameintxt,simpler_model.coef_2)
featurecoef1=dict(featurecoef)

In [42]:
print(sorted(featurecoef1.keys()))

['area_mean', 'area_se', 'area_worst', 'compactness_mean', 'compactness_se', 'compactness_worst', 'concave_points_mean', 'concave_points_se', 'concave_points_worst', 'concavity_mean', 'concavity_se', 'concavity_worst', 'fractal_dimension_mean', 'fractal_dimension_se', 'fractal_dimension_worst', 'perimeter_mean', 'perimeter_se', 'perimeter_worst', 'radius_mean', 'radius_se', 'radius_worst', 'smoothness_mean', 'smoothness_se', 'smoothness_worst', 'symmetry_mean', 'symmetry_se', 'symmetry_worst', 'texture_mean', 'texture_se', 'texture_worst']


In [43]:
sorted(featurecoef1.items(),key=lambda kv:(kv[1], kv[0]))

[('concavity_mean', 8.181537315194337e-48),
 ('area_worst', 4.399001688567259e-47),
 ('compactness_worst', 7.205305026106296e-47),
 ('compactness_se', 9.489090740475517e-47),
 ('concave_points_mean', 1.0907227971485272e-46),
 ('concavity_worst', 1.4568061892949543e-46),
 ('area_se', 1.5593297549699958e-46),
 ('area_mean', 2.5164818875792704e-46),
 ('concavity_se', 3.306994597727629e-46),
 ('symmetry_se', 3.3941649874402352e-46),
 ('radius_se', 4.401803773660866e-46),
 ('symmetry_worst', 4.675163608743322e-46),
 ('smoothness_worst', 4.761821373066846e-46),
 ('symmetry_mean', 4.9129812472856526e-46),
 ('perimeter_se', 4.993502950736556e-46),
 ('fractal_dimension_worst', 6.575395366936892e-46),
 ('smoothness_mean', 7.921719649140838e-46),
 ('concave_points_worst', 8.42090194981654e-46),
 ('fractal_dimension_se', 9.280414643683361e-46),
 ('concave_points_se', 9.660946096439896e-46),
 ('texture_worst', 1.0027007450879271e-45),
 ('smoothness_se', 1.3376558621501548e-45),
 ('compactness_mean'

# Train LimeTree

In [44]:
from sklearn import tree

In [45]:
treemodel=tree.DecisionTreeRegressor(max_depth=5)
treemodel.fit(result,y2,sample_weight=weights)

DecisionTreeRegressor(max_depth=5)

In [46]:
importances = treemodel.feature_importances_

In [47]:
importances

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.09803958,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.09803958,  0.        ,  0.        ,  0.        ,  0.        ])

In [48]:
feature_nameintxt1=['radius_mean','texture_mean', 'perimeter_mean','area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean','concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst']
featureimportances=zip(feature_nameintxt1,importances)
featureimportances1=dict(featureimportances)

In [49]:
print(sorted(featureimportances1.keys()))

['area_mean', 'area_se', 'area_worst', 'compactness_mean', 'compactness_se', 'compactness_worst', 'concave_points_mean', 'concave_points_se', 'concave_points_worst', 'concavity_mean', 'concavity_se', 'concavity_worst', 'fractal_dimension_mean', 'fractal_dimension_se', 'fractal_dimension_worst', 'perimeter_mean', 'perimeter_se', 'perimeter_worst', 'radius_mean', 'radius_se', 'radius_worst', 'smoothness_mean', 'smoothness_se', 'smoothness_worst', 'symmetry_mean', 'symmetry_se', 'symmetry_worst', 'texture_mean', 'texture_se', 'texture_worst']


In [50]:
sorted(featureimportances1.items(),key=lambda kv:(kv[1], kv[0]))

[('concave_points_se', -0.09803958138360953),
 ('area_mean', 0.0),
 ('area_se', 0.0),
 ('area_worst', 0.0),
 ('compactness_mean', 0.0),
 ('compactness_se', 0.0),
 ('concave_points_mean', 0.0),
 ('concave_points_worst', 0.0),
 ('concavity_mean', 0.0),
 ('concavity_se', 0.0),
 ('concavity_worst', 0.0),
 ('fractal_dimension_mean', 0.0),
 ('fractal_dimension_se', 0.0),
 ('fractal_dimension_worst', 0.0),
 ('perimeter_mean', 0.0),
 ('perimeter_se', 0.0),
 ('perimeter_worst', 0.0),
 ('radius_mean', 0.0),
 ('radius_se', 0.0),
 ('radius_worst', 0.0),
 ('smoothness_mean', 0.0),
 ('smoothness_se', 0.0),
 ('smoothness_worst', 0.0),
 ('symmetry_mean', 0.0),
 ('symmetry_se', 0.0),
 ('symmetry_worst', 0.0),
 ('texture_mean', 0.0),
 ('texture_se', 0.0),
 ('texture_worst', 0.0),
 ('compactness_worst', 1.0980395813836095)]

# Train LimeRandomforest

In [51]:
from sklearn.ensemble import RandomForestRegressor

In [52]:
regr_rf=RandomForestRegressor(max_depth=5)
regr_rf.fit(X=result, y=y2,sample_weight=weights)

RandomForestRegressor(max_depth=5)

In [53]:
importances2 = regr_rf.feature_importances_

In [54]:
feature_nameintxt2=['radius_mean','texture_mean', 'perimeter_mean','area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean','concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst']
featureimportances2=zip(feature_nameintxt2,importances2)
featureimportances3=dict(featureimportances2)

In [55]:
print(sorted(featureimportances3.keys()))

['area_mean', 'area_se', 'area_worst', 'compactness_mean', 'compactness_se', 'compactness_worst', 'concave_points_mean', 'concave_points_se', 'concave_points_worst', 'concavity_mean', 'concavity_se', 'concavity_worst', 'fractal_dimension_mean', 'fractal_dimension_se', 'fractal_dimension_worst', 'perimeter_mean', 'perimeter_se', 'perimeter_worst', 'radius_mean', 'radius_se', 'radius_worst', 'smoothness_mean', 'smoothness_se', 'smoothness_worst', 'symmetry_mean', 'symmetry_se', 'symmetry_worst', 'texture_mean', 'texture_se', 'texture_worst']


In [56]:
sorted(featureimportances3.items(),key=lambda kv:(kv[1], kv[0]))

[('concavity_mean', 0.0),
 ('symmetry_se', 0.0),
 ('area_se', 0.0002396896477466396),
 ('radius_mean', 0.002419333863557213),
 ('concave_points_mean', 0.0034682186388692985),
 ('perimeter_worst', 0.012430814218400836),
 ('texture_worst', 0.015746630657977965),
 ('smoothness_mean', 0.01608973967303576),
 ('concave_points_se', 0.016860567408855866),
 ('fractal_dimension_worst', 0.018755609639372846),
 ('compactness_worst', 0.019474216297984084),
 ('radius_se', 0.0230805441539537),
 ('perimeter_mean', 0.025000000000000005),
 ('smoothness_worst', 0.025000000000000005),
 ('symmetry_mean', 0.027440042137687824),
 ('symmetry_worst', 0.028013397660817597),
 ('smoothness_se', 0.028148078708084022),
 ('compactness_se', 0.028847586450845484),
 ('area_mean', 0.02902284678350705),
 ('fractal_dimension_mean', 0.029403327364125972),
 ('radius_worst', 0.03199181488724352),
 ('texture_se', 0.039599367381524996),
 ('concave_points_worst', 0.045034324624456015),
 ('perimeter_se', 0.045082062404964346),
 

# Train XGB Model

In [57]:
import xgboost as xgb

xgbrModel=xgb.XGBRegressor()
xgbrModel.fit(result,y2,sample_weight=weights)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [58]:
importances3=xgbrModel.feature_importances_
importances3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [59]:
importances3.shape

(30,)

In [60]:
feature_nameintxt3=['radius_mean','texture_mean', 'perimeter_mean','area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean','concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst']
featureimportances3=zip(feature_nameintxt3,importances3)
featureimportances4=dict(featureimportances3)

In [61]:
print(sorted(featureimportances4.keys()))

['area_mean', 'area_se', 'area_worst', 'compactness_mean', 'compactness_se', 'compactness_worst', 'concave_points_mean', 'concave_points_se', 'concave_points_worst', 'concavity_mean', 'concavity_se', 'concavity_worst', 'fractal_dimension_mean', 'fractal_dimension_se', 'fractal_dimension_worst', 'perimeter_mean', 'perimeter_se', 'perimeter_worst', 'radius_mean', 'radius_se', 'radius_worst', 'smoothness_mean', 'smoothness_se', 'smoothness_worst', 'symmetry_mean', 'symmetry_se', 'symmetry_worst', 'texture_mean', 'texture_se', 'texture_worst']


In [62]:
sorted(featureimportances4.items(),key=lambda kv:(kv[1], kv[0]))

[('area_mean', 0.0),
 ('area_se', 0.0),
 ('area_worst', 0.0),
 ('compactness_mean', 0.0),
 ('compactness_se', 0.0),
 ('compactness_worst', 0.0),
 ('concave_points_mean', 0.0),
 ('concave_points_se', 0.0),
 ('concave_points_worst', 0.0),
 ('concavity_mean', 0.0),
 ('concavity_se', 0.0),
 ('concavity_worst', 0.0),
 ('fractal_dimension_mean', 0.0),
 ('fractal_dimension_se', 0.0),
 ('fractal_dimension_worst', 0.0),
 ('perimeter_mean', 0.0),
 ('perimeter_se', 0.0),
 ('perimeter_worst', 0.0),
 ('radius_mean', 0.0),
 ('radius_se', 0.0),
 ('radius_worst', 0.0),
 ('smoothness_mean', 0.0),
 ('smoothness_se', 0.0),
 ('smoothness_worst', 0.0),
 ('symmetry_mean', 0.0),
 ('symmetry_se', 0.0),
 ('symmetry_worst', 0.0),
 ('texture_mean', 0.0),
 ('texture_se', 0.0),
 ('texture_worst', 0.0)]